gui:
  theme:
    selectedLineBgColor:
      - reverse
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#6c7086'
    cherryPickedCommitFgColor:
      - '#a6e3a1'
  skipDiscardChangeWarning: true
  showIcons: true
  mouseEvents: true
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  autoFetch: true
  autoRefresh: true
